### ISSUE TITLE
Inconsistent use of placeholder values in SAAS Registry Documentation

### ISSUE THREAD

**Issue by bmcdonn2** [SAP/cloud-cf-multitenant-Inventory-management#1]
I found an inconsistency with the placeholder for the backend app URL in the SAAS Registry section of the download/installation instructions.

For example, the SAAS registry config file contains a placeholder **<`Your back-end app URL`>** to indicate the `onSubscription` URL. The example of what that would look like points to the `inventorymanagementbackend` app"

https://github.com/SAP/cloud-cf-multitenant-Inventory-management/blob/4fc53d1d2b3253245cd6b1b6e071409dccb6d0ae/Download_and_Installation_Instructions.md#L97-L101

Yet later on when providing details on what URL should be returned by the onboarding service, the same placeholder  **<`Your back-end app URL`>** is used but this time the `inventorymanagementui` app is referenced

https://github.com/SAP/cloud-cf-multitenant-Inventory-management/blob/4fc53d1d2b3253245cd6b1b6e071409dccb6d0ae/Download_and_Installation_Instructions.md#L116-L120

So what we're seeing is that in one context, **<`Your back-end app URL`>** corresponds to `inventorymanagementbackend` while in another it corresponds to `inventorymanagementui`. Can this be revised to make it more clear which one is actually the backend app?

**Comment by prathik457** [comment]
Did you get it clarified as to what needs to be used here? UI or backend URL?

**Comment by bmcdonn2** [comment]
I eventually figured it out. Just thought I'd raise the issue in case others had the same confusion I did.

To be clear, the URL's should be set as follows:

1. In the saas-registry: `onSubscription` should point to the that application serves the endpoint for tenant onboarding. In this case the backend app.
2. In the index.js: The URL returned by the onboarding service should be for the application that has the approuter. In this case it's the UI app.

**Comment by sandeep-tds** [comment]
> I found an inconsistency with the placeholder for the backend app URL in the SAAS Registry section of the download/installation instructions.
> 
> For example, the SAAS registry config file contains a placeholder **<`Your back-end app URL`>** to indicate the `onSubscription` URL. The example of what that would look like points to the `inventorymanagementbackend` app"
> 
> [cloud-cf-multitenant-Inventory-management/Download_and_Installation_Instructions.md](https://github.com/SAP/cloud-cf-multitenant-Inventory-management/blob/4fc53d1d2b3253245cd6b1b6e071409dccb6d0ae/Download_and_Installation_Instructions.md#L97-L101)
> 
> Lines 97 to 101 in [4fc53d1](/SAP/cloud-cf-multitenant-Inventory-management/commit/4fc53d1d2b3253245cd6b1b6e071409dccb6d0ae)
> 
>  6.  In the **mtconfig/config.json** file, replace the **<`Your back-end app URL`>** placeholder with your backend app’s URL including the CF domain. 
>   
>      The URL for your **onSubscription** parameter should now look something like this: 
>   
>      `https://inventorymanagementbackend.<CF Domain>/callback/v1.0/tenants/{tenantId}` 
> Yet later on when providing details on what URL should be returned by the onboarding service, the same placeholder **<`Your back-end app URL`>** is used but this time the `inventorymanagementui` app is referenced
> 
> [cloud-cf-multitenant-Inventory-management/Download_and_Installation_Instructions.md](https://github.com/SAP/cloud-cf-multitenant-Inventory-management/blob/4fc53d1d2b3253245cd6b1b6e071409dccb6d0ae/Download_and_Installation_Instructions.md#L116-L120)
> 
> Lines 116 to 120 in [4fc53d1](/SAP/cloud-cf-multitenant-Inventory-management/commit/4fc53d1d2b3253245cd6b1b6e071409dccb6d0ae)
> 
>  9. In the **index.js** file, replace the **<`Your back-end app`>** placeholder with your backend app’s URL including the CF domain. **Do not include the HTTP/HTTPS protocol.** 
>   
>      Your **tenantAppURL** parameter should now look something like this: 
>   
>      `var tenantAppURL = "https:\/\/" + consumerSubdomain + "-inventorymanagementui.<CF Domain>";` 
> So what we're seeing is that in one context, **<`Your back-end app URL`>** corresponds to `inventorymanagementbackend` while in another it corresponds to `inventorymanagementui`. Can this be revised to make it more clear which one is actually the backend app?

@bmcdonn2  Thank you so much for bringing this inconsistency to our attention. [We have updated the documentation ](https://github.com/SAP/cloud-cf-multitenant-Inventory-management/blob/master/Download_and_Installation_Instructions.md)and the corresponding code file.
